all: clean prepare build_js build_css build_thirdparty ;

js_files=../dui/DAAccountSelector.js \
	../dui/DAGrid.js \
	../dui/DANumberPulldown.js \
	../common/DA/DA-min.js \
	../common/io/io.js \
	../common/io/json-io.js \
	../common/layout/simpleviewport.js \
	../common/calendar/calendar.js \
	../common/calendar/selector.js \
	../common/calendar/rangeselector.js \
	../common/calendar/timerangeslider.js \
	../common/calendar/textcalendar.js \
	../common/account/selector.js \
	../common/account/controller.js \
	./scheduler.js \
	./pages/edit.js

css_files=../../../../libraries/extjs/v2.1/resources/css/combo.css \
	../../../../libraries/extjs/v2.1/resources/css/core.css \
	../../../../libraries/extjs/v2.1/resources/css/form.css \
	../../../../libraries/extjs/v2.1/resources/css/qtips.css \
	../../../../libraries/extjs/v2.1/resources/css/resizable.css \
	../common/layout/simpleviewport.css \
	../common/calendar/calendar.css \
	../common/calendar/timerangeslider.css \
	../common/account/selector.css \
	../common/reset/reset-min.css

thirdparty_js_files=../../../../libraries/prototype/v1.6.0_rc1/prototype.js \
	../../../../libraries/extjs/v2.1/adapter/ext/ext-base.js \
	../../../../libraries/extjs/v2.1/ext-all.js \
	../../../../libraries/extjs/v2.1/ux/Ext.ux.SlideZone.js

include ../common/Makefile-common.mk
